export default {
  Image: "image/jpeg",
  Audio: "audio/mpeg",
  Video: "video/mp4",
  Text: "text/plain",
  Application: "application/xhtml+xml",
  Font: "application/font-woff",
  XML: "application/xml",
  CSS: "text/css",
  JS: "text/javascript",
  JSON: "application/json",
  SVG: "image/svg+xml",
  HTML: "text/html",
  PDF: "application/pdf",
  ZIP: "application/zip",
};
